name: Run tests with Tox

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        include:
          - os: ubuntu-20.04
            python: '3.6'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py  # Run tox using the version of Python in `PATH`
